#!/bin/bash

source ~/anaconda3/etc/profile.d/conda.sh
conda activate dataenv

service redis-server stop
redis-server /etc/redis/redis.conf
redis-cli flushall
sleep 1

python -m pipert.contrib.flask_display -i camera:0 -m camera:2 -z 4246 &
PID1=$!
#python -m contrib.cv2_display -i camera:1 -z 4245 &
#PID2=$!
#python -m contrib.canny -i camera:0 -o camera:1 -z 4244 &
#PID3=$!
#python -m contrib.face_detection -i camera:0 -o camera:3 -z 4243 &
#PID7=$!
python -m pipert.contrib.yolov3 -i camera:0 -o camera:2 -z 4243 &
PID4=$!
#python -m pipert.contrib.sort -i camera:2 -o camera:3 -z 4247 --percent-seen 0.6 &
#PID6=$!
sleep 5
#python -m contrib.vid_capture -i contrib/test.mp4 &
python -m pipert.contrib.vid_capture -i "udp://239.101.101.1:1234" &
PID5=$!

read -p "Press enter to continue\n"

#sleep 40
kill -SIGTERM $PID1
#kill $PID2
#kill $PID3
kill -SIGTERM $PID4
kill -SIGTERM $PID5
#kill -SIGTERM $PID6
#kill $PID7

sleep 5
kill -9 $PID1
#kill $PID2
#kill $PID3
kill -9 $PID4
kill -9 $PID5
#kill -9 $PID6
#kill $PID

sleep 1

redis-cli flushall
redis-cli shutdown
