#!/bin/bash

#source ~/anaconda3/etc/profile.d/conda.sh
#conda activate dataenv

#service redis-server stop
#redis-server /etc/redis/6379.conf
#redis-cli flushall
#sleep 1

#REDIS_URL=${REDIS_URL:='redis://localhost:6379'}
REDIS_URL=${REDIS_URL:='redis://127.0.0.1:6379'}

python -m pipert.contrib.flask_display -u "$REDIS_URL" -i camera:2 -m camera:3 -z 4246 &
PID1=$!
#python -m contrib.cv2_display -u "$REDIS_URL" -i camera:1 -z 4245 &
#PID2=$!
#python -m contrib.canny -u "$REDIS_URL" -i camera:0 -o camera:1 -z 4244 &
#PID3=$!
python -m pipert.contrib.face_detection -s True -u "$REDIS_URL" -i camera:0 -o camera:3 -of camera:2 -z 4243 &
PID7=$!
#python -m pipert.contrib.pose_estimation -u "$REDIS_URL" -i camera:0 -o camera:3 -z 4249 &
#PID8=$!
#python -m pipert.contrib.yolov3 -u "$REDIS_URL" -i camera:0 -o camera:2 -z 4243 &
#PID4=$!
#python -m pipert.contrib.sort -u "$REDIS_URL" -i camera:2 -o camera:3 -z 4247 --max-age 10 --window-size 10 --percent-seen 0.6 &
#PID6=$!
#python -m pipert.contrib.video_writer -z 4248 &
#PID9=$!
sleep 5
#python -m pipert.contrib.vid_capture -i pipert/contrib/test.mp4 &
python -m pipert.contrib.vid_capture -s True -u "$REDIS_URL" &
PID5=$!

sleep 1200
kill $PID1
kill $PID2
kill $PID3
kill $PID4
kill $PID5
kill $PID6
kill $PID7
kill -SIGTERM $PID8
kill $PID9

sleep 5
kill -9 $PID1
kill $PID2
kill $PID3
kill -9 $PID4
kill -9 $PID5
kill -9 $PID6
kill -9 $PID8
kill -9 $PID9

sleep 1
redis-cli flushall
redis-cli shutdown
