FROM pipert_base-pipert

# Set up SSH server
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:admin' |chpasswd
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN mkdir /root/.ssh
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 22
EXPOSE 5000

# Copy all necessary files for PipeRT
COPY . /root

# Set up environment variables

RUN echo "export PYTHONPATH=/root" >> /etc/profile && \
    echo "export PYTHONUNBUFFERED=1" >> /etc/profile && \
    echo "export REDIS_URL=redis://redis:6379/0" >> /etc/profile && \
    echo "export UI=false" >> /etc/profile && \
    echo "export UI_PORT=5005" >> /etc/profile && \
    echo "export CLI_ENDPOINT=4001" >> /etc/profile

CMD ["/usr/sbin/sshd", "-D"]