#!/bin/bash

source ~/anaconda3/etc/profile.d/conda.sh
conda activate dataenv

service redis-server stop
redis-server /etc/redis/6379.conf
redis-cli flushall
sleep 2

python -m contrib.flask_display -i camera:0 -m camera:3 -z 4246 &
PID1=$!
python -m contrib.face_detection -i camera:0 -o camera:3 -z 4243 &
PID4=$!
sleep 3
python -m contrib.drone_capture &
PID5=$!

sleep 90
kill $PID1
kill $PID4
kill $PID5

sleep 3

redis-cli flushall
redis-cli shutdown

