{
 "title": "Pipert Components",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "component",
    "query": "label_values(routine_processing_seconds_bucket, component)"
   },
   {
    "name": "routine",
    "query": "label_values(routine_processing_seconds_bucket{component=~\"$component\"}, routine)"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Average requests per second for $routine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "routine",
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_count{component=~\"^$component\", routine=\"$routine\"}[5m])",
     "legendFormat": "{{routine}}"
    }
   ]
  },
  {
   "title": "Average requests per second for $routine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_count{component=~\"^$component\", routine=\"$routine\"}[5m])",
     "legendFormat": "{{routine}}"
    }
   ]
  },
  {
   "title": "Requests per second over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_count{component=~\"^$component\"}[5m])",
     "legendFormat": "{{component}}: {{routine}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$routine Average execution time ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "routine",
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_sum{component=~\"$component\", routine=~\"$routine\"}[$__interval])/rate(routine_processing_seconds_count[$__interval])"
    }
   ]
  },
  {
   "title": "$routine Average execution time ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_sum{component=~\"$component\", routine=~\"$routine\"}[$__interval])/rate(routine_processing_seconds_count[$__interval])"
    }
   ]
  },
  {
   "title": "$routine execution time percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "repeat": "routine",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(routine_processing_seconds_bucket{routine=~\"^$routine\", component=~\"^$component\"}[5m])) by (le, routine))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.75, sum(rate(routine_processing_seconds_bucket{routine=~\"^$routine\", component=~\"^$component\"}[5m])) by (le, routine))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": " histogram_quantile(0.5, sum(rate(routine_processing_seconds_bucket{routine=~\"^$routine\", component=~\"^$component\"}[5m])) by (le, routine))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "rate(routine_processing_seconds_sum{routine=~\"^$routine\", component=~\"^$component\"}[5m]) / rate(routine_processing_seconds_count{routine=~\"^$routine\", component=~\"^$component\"}[5m]) ",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "$routine execution time percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(routine_processing_seconds_bucket{routine=~\"^$routine\", component=~\"^$component\"}[5m])) by (le, routine))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.75, sum(rate(routine_processing_seconds_bucket{routine=~\"^$routine\", component=~\"^$component\"}[5m])) by (le, routine))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": " histogram_quantile(0.5, sum(rate(routine_processing_seconds_bucket{routine=~\"^$routine\", component=~\"^$component\"}[5m])) by (le, routine))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "rate(routine_processing_seconds_sum{routine=~\"^$routine\", component=~\"^$component\"}[5m]) / rate(routine_processing_seconds_count{routine=~\"^$routine\", component=~\"^$component\"}[5m]) ",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "95th execution time percentile per routine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(routine_processing_seconds_bucket{component=~\"^$component\", routine=~\"^$routine\"}[5m])) by (le, component, routine))",
     "legendFormat": "{{routine}}"
    }
   ]
  }
 ]
}