{
 "title": "Pipert Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "component",
    "query": "label_values(routine_processing_seconds_bucket, component)"
   },
   {
    "name": "routine",
    "query": "label_values(routine_processing_seconds_bucket{component=~\"$component\"}, routine)"
   }
  ]
 },
 "panels": [
  {
   "title": "total routine execution time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(routine_processing_seconds_sum{component=~\"$component\", routine=~\"$routine\"}[$__range])/rate(routine_processing_seconds_count{component=~\"$component\", routine=~\"$routine\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Execution time Pie chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_sum{component=~\"$component\", routine=~\"$routine\"}[$__range])/rate(routine_processing_seconds_count{component=~\"$component\", routine=~\"$routine\"}[$__range])",
     "legendFormat": "{{component}} : {{routine}}"
    }
   ]
  },
  {
   "title": "95th execution time percentile per routine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(routine_processing_seconds_bucket{component=~\"^$component\", routine=~\"^$routine\"}[5m])) by (le, component, routine))",
     "legendFormat": "{{component}}: {{routine}}"
    }
   ]
  },
  {
   "title": "Requests per second over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_count{component=~\"^$component\"}[5m])",
     "legendFormat": "{{component}}: {{routine}}"
    }
   ]
  },
  {
   "title": "average execution time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(routine_processing_seconds_sum{component=~\"$component\", routine=~\"$routine\"}[$__interval])/rate(routine_processing_seconds_count{component=~\"$component\", routine=~\"$routine\"}[$__interval])",
     "legendFormat": "{{component}}: {{routine}}"
    }
   ]
  },
  { "title": "Live Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Live Video",
   "type": "text",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "content": "<img src=\"http://localhost:5000/video\"></img>\n\n\n"
  }
 ]
}